#!/bin/sh

mkdir -p /home/chris11/projects/def-stbil30/chris11/20240308_mmus_prostate_EAW/output/rna-pipeline_mmus_prostate_EAW-GRCh38_PE/featureCounts_s2

sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_CTL_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_CTL_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_CTL_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_CTL_rep4_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_E2_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_E2_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_E2_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_E2_rep4_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_ET_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_ET_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_ET_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_ET_rep4_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_T_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_T_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_T_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_Normal_RNA_T_rep4_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_CTL_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_CTL_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_CTL_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_E2_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_E2_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_E2_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_E2_rep4_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_ET_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_ET_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_ET_rep3_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_ET_rep4_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_T_rep1_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_T_rep2_s2.sh
sbatch scripts/rnaseq_mus_prostate_EAW_pipeline/05_featureCounts/batch_sh/featureCounts_PCa_RNA_T_rep3_s2.sh